# Generated by Django 4.0.4 on 2023-05-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_song_audio_type_alter_song_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='allowed_emails',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_type',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Protected', 'Protected')], default='Public', max_length=20),
        ),
    ]
